### ISSUE TITLE
TypeError: Cannot read property 'route' of undefined

### ISSUE THREAD

**Issue by LiuWeiMr** [Dess-Li/egg-rmq#1]
`E:\egg-test\egg-example\node_modules\egg\lib\application.js:69
      throw e;
      ^

TypeError: Cannot read property 'route' of undefined
    at module.exports.app (E:\egg-test\egg-example\app\router.js:31:9)
    at AppWorkerLoader.loadFile (E:\egg-test\egg-example\node_modules\egg-core\lib\loader\egg_loader.js:303:13)
    at AppWorkerLoader.loadRouter (E:\egg-test\egg-example\node_modules\egg-core\lib\loader\mixin\router.js:17:10)
    at AppWorkerLoader.load (E:\egg-test\egg-example\node_modules\egg\lib\loader\app_worker_loader.js:41:10)
    at new Application (E:\egg-test\egg-example\node_modules\egg\lib\application.js:65:19)
    at Object.<anonymous> (E:\egg-test\egg-example\node_modules\egg-cluster\lib\app_worker.js:20:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3`

按照官方示例使用出错：

配置：
`// {app_root}/config/plugin.js
exports.rmq = {
    enable: true,
    package: 'egg-rmq',
};`
`// {app_root}/config/config.default.js
config.rmq = {
        host: 'amqp://admain:admain@192.168.2.19:5672',
    };`

示例：
`// {app_root}/rmq/controller/hello.js
module.exports = app => {
    return class TestController extends app.Controller {
      async test() {
        const { ctx } = this;
        await ctx.req.ch.assertQueue(ctx.req.queue, { durable: false });
        ctx.req.ch.consume(ctx.req.queue, msg => {
          console.log(' [x] Received %s', msg.content.toString());
          console.log(msg.properties.headers, '#hello headers');
        }, { noAck: true });
        ctx.req.ch.sendToQueue(ctx.req.queue, Buffer.from('Nodejs'), { headers: { user: 'user test' } });
      }
    };
  };`
`// {app_root}/router.js
module.exports = app => {
  const { router, controller, rmq } = app;
  rmq.route('hello', rmq.controller.listener.test); // hello is queue
};`

我打印app，没有rmq属性：
:::::app { env: 'local',
  name: 'example',
  baseDir: 'E:\\egg-test\\egg-example',
  subdomainOffset: 2,
  config: '<egg config>',
  controller: '<egg controller>',
  httpclient: '<egg httpclient>',
  loggers: '<egg loggers>',
  middlewares: '<egg middlewares>',
  router: '<egg router>',
  serviceClasses: '<egg serviceClasses>' }

**Comment by dessli** [comment]
请升级包至1.0.4
